In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [4]:
df = pd.read_csv("Top Indian Places to Visit.csv")
df.head()

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
0,0,Northern,Delhi,Delhi,India Gate,War Memorial,1921,0.5,4.6,0,Yes,NaN,Historical,Yes,2.60,Evening
1,1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,NaN,Historical,Yes,0.40,Afternoon
2,2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,NaN,Religious,No,0.40,Afternoon
3,3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening
4,4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,NaN,Scientific,Yes,0.31,Morning

In [5]:
df.shape

(325, 16)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        325 non-null    int64
 1   Zone                              325 non-null    object
 2   State                             325 non-null    object
 3   City                              325 non-null    object
 4   Name                              325 non-null    object
 5   Type                              325 non-null    object
 6   Establishment Year                325 non-null    object
 7   time needed to visit in hrs       325 non-null    float64
 8   Google review rating              325 non-null    float64
 9   Entrance Fee in INR               325 non-null    int64
 10  Airport with 50km Radius          325 non-null    object
 11  Weekly Off                        32 non-null     object
 12  Significance                      325 non-null    object
 13  DSLR Allowed                      325 non-null    object
 14  Number of google review in lakhs  325 non-null    float64
 15  Best Time to visit                325 non-null    object
dtypes: float64(3), int64(2), object(11)
memory usage: 40.8+ KB

In [7]:
df.drop("Unnamed: 0", axis=1, inplace=True)
df.drop("Weekly Off", axis=1, inplace=True)

In [8]:
df.head()

,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
0,Northern,Delhi,Delhi,India Gate,War Memorial,1921,0.5,4.6,0,Yes,Historical,Yes,2.60,Evening
1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,Historical,Yes,0.40,Afternoon
2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,Religious,No,0.40,Afternoon
3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Environmental,Yes,0.27,Evening
4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,Scientific,Yes,0.31,Morning

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df[df["Name"]=="Abbey Falls"]

,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
113,Southern,Karnataka,Coorg,Abbey Falls,Waterfall,Unknown,1.0,4.1,0,No,Nature,Yes,0.03,Morning

# Popularity Based Recommender System

In [11]:
rating_df = pd.DataFrame({'Name': df["Name"],
                              'Number of google review in lakhs': df["Number of google review in lakhs"],
                              'Google review rating': df["Google review rating"]
                              })
rating_df

,Name,Number of google review in lakhs,Google review rating
0,India Gate,2.60,4.6
1,Humayun's Tomb,0.40,4.5
2,Akshardham Temple,0.40,4.6
3,Waste to Wonder Park,0.27,4.1
4,Jantar Mantar,0.31,4.2
...,...,...,...
320,Akshardham,0.18,4.6
321,Agra Fort,1.30,4.5
322,Madhya Pradesh Tribal Museum,0.15,4.7
323,City Palace,0.51,4.4
324,Albert Hall Museum,0.63,4.5

In [12]:
popularity_df = df[rating_df['Number of google review in lakhs']>=0.5].sort_values('Google review rating',ascending=False)
popularity_df

,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
92,Northern,Punjab,Amritsar,Golden Temple (Harmandir Sahib),Religious Site,1604,1.5,4.9,0,Yes,Spiritual,Yes,1.90,All
20,Western,Maharastra,Mumbai,Siddhivinayak Temple,Temple,1881,2.0,4.8,0,Yes,Religious,No,1.05,All
305,Northern,Delhi,New Delhi,Gurudwara Bangla Sahib,Gurudwara,Unknown,1.0,4.8,0,Yes,Religious,Yes,1.05,All
140,Central,Madhya Pradesh,Ujjain,Mahakaleshwar Jyotirlinga,Temple,-3500,1.5,4.8,0,Yes,Religious,No,1.20,All
130,Western,Maharastra,Kolhapur,Mahalakshmi Temple,Temple,700,1.0,4.8,0,Yes,Religious,No,0.90,All
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,Southern,Telangana,Hyderabad,Nehru Zoological Park,Zoo,1963,3.0,4.2,50,Yes,Wildlife,Yes,0.86,Morning
54,Southern,Goa,Goa,Fort Aguada,Fort,1612,1.5,4.2,0,Yes,Historical,Yes,0.95,Morning
41,Southern,Telangana,Hyderabad,Lumbini Park,Park,1994,1.0,4.1,20,Yes,Recreational,Yes,0.73,Evening
240,Southern,Tamil Nadu,Ooty,Ooty Lake,Lake,1824,1.0,4.1,10,Yes,Recreational,Yes,0.61,Morning
26,Western,Maharastra,Lonavala,Imagicaa,Amusement Park,2013,5.0,1.4,1149,No,Recreational,Yes,0.95,All

# Content based Filtering

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer  # using for chech which word is more important in the document
from sklearn.metrics.pairwise import cosine_similarity





features = ['Zone', 'State', 'City', 'Type', 'Significance']
for feature in features:
    df[feature] = df[feature].fillna('').str.lower()



def create_soup(x):
    return f"{x['Zone']} {x['State']} {x['City']} {x['Type']} {x['Significance']}"

df['soup'] = df.apply(create_soup, axis=1)

#  Vectorize the Soup using TF-IDF
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['soup'])

#  Compute the Similarity Matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)


def get_recommendations(place_name, cosine_sim=cosine_sim):
    # Get index of the place that matches the name
    try:
        idx = df[df['Name'].str.lower() == place_name.lower()].index[0]
    except IndexError:
        return "Place not found in dataset."


    sim_scores = list(enumerate(cosine_sim[idx]))


    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)


    sim_scores = sim_scores[1:6]


    place_indices = [i[0] for i in sim_scores]


    return df[['Name', 'City', 'Type', 'Google review rating']].iloc[place_indices]


print(get_recommendations("Taj Mahal"))

              Name     City       Type  Google review rating
321      Agra Fort     agra       fort                   4.5
120     Gol Gumbaz  bijapur  mausoleum                   4.5
188    Jhansi Fort   jhansi       fort                   4.4
192   Aligarh Fort  aligarh       fort                   4.1
183  Bara Imambara  lucknow   monument                   4.4

In [16]:
import pickle

data_file = "india_travel_list.pkl"
similarity_file = "similarity_matrix.pkl"
popullarity_file = "popularity_df.pkl"

pickle.dump(df, open(data_file, 'wb'))

pickle.dump(cosine_sim, open(similarity_file, 'wb'))

pickle.dump(popularity_df, open(popullarity_file, 'wb'))

print("Model saved successfully!")

Model saved successfully!